### ISSUE TITLE
How to extend the functionality of this gem

### ISSUE THREAD

**Issue by jaykilleen** [asanghi/fiscali#11]
Hi,

I am still learning Ruby and Rails. I'd like to define my own method on this that does the following.

Assuming I am in financial year 2014 I can call `Date.today.financial_periods` and have an array `[201501,201502,201503,201504,201505,201506,201507,201508,201509,201510,201511,201512]` returned.

Where would I put this to define it? 

I have tried creating a new file under my lib directory called fiscali.rb and adding

``` ruby
module RisingSun
  module Fiscali
    def financial_periods
      year = self.financial_year
      financial_periods = []
      (1..12).each do |period|
        period.format("%02d",4)
        financial_periods << period
      end
    end
  end
end
```

But no luck... :confounded:

**Comment by chiperific** [comment]
You are on the right track.

First, don't use 'financial_periods' as a variable since it's also your
method name. You can call it anything and it will be returned since it's
the last action in your code.

Second, you added your financial_periods method to the Fiscali module, not
the date module. You should explore how to add this method to the Date
class.

Note that you want to call 'Date.today.financial_periods', so it needs to
live inside Date.

**Comment by maxwell** [comment]
Would still love a pull request if you would find this method useful.
